variable "github_app_owner" {
  type        = string
  description = "The owner of the existing github app to authenticate."
}

variable "github_token" {
  type        = string
  description = "The token generated by gh cli in the github action. An existing github app needs to exist."
  sensitive   = true
}

variable "github_repository_environments" {
  type = list(object({
    environment_name    = string
    repository          = string
    existing            = optional(bool, false)
    wait_timer          = optional(number)
    can_admins_bypass   = optional(bool, true)
    prevent_self_review = optional(bool, false)

    reviewers = optional(object({
      teams = optional(list(string))
      users = optional(list(string))
    }))

    deployment_branch_policy = optional(object({
      protected_branches     = optional(bool, false)
      custom_branch_policies = optional(bool, false)
      branch_pattern         = optional(list(string), [])
      tag_pattern            = optional(list(string), [])
    }), null)
  }))

  description = <<DESCRIPTION
    A map of Github repository environments to create. The schema is as follows:

    github_repository_environments: (optional list of objects)
      - environment_name:    string                - (Required) The name of the environment.
        repository:          string                - (Required) The repository of the environment. The repository must already exist in github.
        wait_timer:          optional(number)      - (Optional) Amount of time to delay a job after the job is initially triggered.
        can_admins_bypass:   optional(bool, true)  - (Optional) Can repository admins bypass the environment protections.
        prevent_self_review: optional(bool, false) - (Optional) Whether or not a user who created the job is prevented from approving their own job.

        reviewers: (optional object)
            teams: optional(list(string)) - Up to 6 IDs for teams who may review jobs that reference the environment. Reviewers must have at least read access to the repository. Only one of the required reviewers needs to approve the job for it to proceed.     
            users: optional(list(string)) - Up to 6 IDs for users who may review jobs that reference the environment. Reviewers must have at least read access to the repository. Only one of the required reviewers needs to approve the job for it to proceed.

        deployment_branch_policy: (Optional object)
            protected_branches:     bool                   - Whether only branches with branch protection rules can deploy to this environment.
            custom_branch_policies: bool                   - Whether only branches that match the specified name patterns can deploy to this environment. If true then either tag_pattern or branch pattern must be specified.
            branch_pattern:         optional(list(string)) - The name pattern that branches must match in order to deploy to the environment. If not specified, tag_pattern must be specified.
            tag_pattern:            optional(list(string)) - The name pattern that tags must match in order to deploy to the environment. If not specified, branch_pattern must be specified.
  DESCRIPTION
}